/*	Copyright 2007 	Edwin Stang (edwinstang@gmail.com)

    This file is part of JDPlay.

    JDPlay is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    JDPlay is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with JDPlay.  If not, see <http://www.gnu.org/licenses/>.
*/

/****************************************************************************************************************/

/* JDPlay_jni.cpp:
 *  
 * 	This file implements the JNI for the C++ class.
 *	These functions can be accessed in Java via the JDPlay class shipped with coopnet. 
 *
 * 	This code was created by cxxwrap, a tool to create JNI code from a c++ header file.
 * 	Do not edit this file!
 */

/****************************************************************************************************************/
 
#include "jni.h"
#include "..\\JDPlay\\JDPlay.h"
#ifdef __cplusplus
	extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_jdplay_JDPlay__1_1c16(JNIEnv* __env, jobject __jobj, jstring playerName, jint maxSearchRetries, jboolean debug)
{
	const char* __TplayerName = playerName == 0 ? NULL : __env->GetStringUTFChars(playerName, NULL);
	JDPlay* __obj = new JDPlay((char*)__TplayerName, (int)maxSearchRetries, (bool)debug);
	if (playerName != 0) __env->ReleaseStringUTFChars(playerName, __TplayerName);
	return (jlong) __obj;
}

JNIEXPORT void JNICALL Java_jdplay_JDPlay__1_1m18(JNIEnv* __env, jobject, jlong __imp, jstring playerName)
{
	JDPlay* __obj = (JDPlay*) __imp;
	const char* __TplayerName = playerName == 0 ? NULL : __env->GetStringUTFChars(playerName, NULL);
	__obj->updatePlayerName((char*)__TplayerName);
	if (playerName != 0) __env->ReleaseStringUTFChars(playerName, __TplayerName);
}

JNIEXPORT jboolean JNICALL Java_jdplay_JDPlay__1_1m19(JNIEnv* __env, jobject, jlong __imp, jstring gameGUID, jstring hostIP, jboolean isHost)
{
	JDPlay* __obj = (JDPlay*) __imp;
	const char* __TgameGUID = gameGUID == 0 ? NULL : __env->GetStringUTFChars(gameGUID, NULL);
	const char* __ThostIP = hostIP == 0 ? NULL : __env->GetStringUTFChars(hostIP, NULL);
	bool __retval = __obj->initialize((char*)__TgameGUID, (char*)__ThostIP, (bool)isHost);
	if (gameGUID != 0) __env->ReleaseStringUTFChars(gameGUID, __TgameGUID);
	if (hostIP != 0) __env->ReleaseStringUTFChars(hostIP, __ThostIP);
	return (jboolean) __retval;
}

JNIEXPORT jboolean JNICALL Java_jdplay_JDPlay__1_1m20(JNIEnv* __env, jobject, jlong __imp, jboolean searchForSession)
{
	JDPlay* __obj = (JDPlay*) __imp;
	bool __retval = __obj->launch((bool)searchForSession);
	return (jboolean) __retval;
}

JNIEXPORT void JNICALL Java_jdplay_JDPlay__1_1d(JNIEnv* __env, jobject, jlong __imp)
{
	JDPlay* __obj = (JDPlay*) __imp;
	delete __obj;
}

#ifdef __cplusplus
	}
#endif
